name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        linter:
          - name: Flake8
            run: flake8
          - name: isort
            run: isort --color --verbose --ignore-whitespace .
          - name: mypy
            run: mypy -p proc_wrapper
    runs-on: ubuntu-latest
    env:
      working-directory: cloudreactor-python-api-client
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Install Dependencies
        run: poetry install
        working-directory: ${{ env.working-directory }}
      - name: ${{ matrix.linter.name }}
        run: poetry run ${{ matrix.linter.run }}
        working-directory: ${{ env.working-directory }}
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - 3.10
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Install Dependencies
        run: poetry install
        working-directory: ${{ env.working-directory }}
      - name: Test with Pytest
        run: poetry run pytest --cov=./ --cov-report=xml
        working-directory: ${{ env.working-directory }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        working-directory: ${{ env.working-directory }}
        with:
          verbose: true

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Install Dependencies
        run: poetry install -E docs
      - name: Build docs
        working-directory: cloudreactor-python-api-client/docs
        run: poetry run make html
