name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        linter:
          - name: Flake8
            run: flake8
          - name: isort
            run: isort --color --verbose --ignore-whitespace .
          - name: mypy
            run: mypy -p cloudreactor_api_client
    runs-on: ubuntu-latest
    env:
      working-directory: cloudreactor-api-client
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Install Dependencies
        run: poetry install
        working-directory: ${{ env.working-directory }}
      - name: ${{ matrix.linter.name }}
        run: poetry run ${{ matrix.linter.run }}
        working-directory: ${{ env.working-directory }}
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    env:
      working-directory: cloudreactor-api-client
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.1.0
      - name: Install Dependencies
        run: poetry install
        working-directory: ${{ env.working-directory }}
      - name: Test with Pytest
        run: poetry run pytest --cov=./ --cov-report=xml
        working-directory: ${{ env.working-directory }}
        env:
          CLOUDREACTOR_API_BASE_URL: ${{ secrets.CLOUDREACTOR_API_BASE_URL }}
          CLOUDREACTOR_API_KEY: ${{ secrets.CLOUDREACTOR_API_KEY }}
          CLOUDREACTOR_SAMPLE_RUN_ENVIRONMENT_NAME:  ${{ secrets.CLOUDREACTOR_SAMPLE_RUN_ENVIRONMENT_NAME }}
          CLOUDREACTOR_SAMPLE_TASK_NAME: aws-ecs-cloudreactor-deployer-sample_smoke_staging
        # The test suite only includes integration tests which shouldn't run
        # in cloned repositories, since the home repository secrets won't be
        # available.
        if: github.repository_owner	== 'CloudReactor'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ${{ env.working-directory }}
          verbose: true

  # Not working -- disable for now
  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: 3.9
  #     - uses: abatilo/actions-poetry@v2.1.0
  #     - name: Install Dependencies
  #       run: poetry install -E docs
  #       working-directory: cloudreactor-api-client
  #     - name: Build docs
  #       working-directory: cloudreactor-api-client/docs
  #       run: poetry run make html
